### ISSUE TITLE
java.lang.NoClassDefFoundError after upgrading to 1.4.0

### ISSUE THREAD

**Issue by peavers** [awslabs/aws-serverless-java-container#297]
* Framework version: 2.2.x
* Implementations: Spring Boot

## Scenario
When updating to the latest 1.4 I'm getting the following error thrown 
```
Error loading class StreamLambdaHandler: org/springframework/boot/context/embedded/EmbeddedServletContainer: java.lang.NoClassDefFoundError
```
Dropping back down to 1.3.2 and everything works again as expected. 

## Expected behavior
Upgrading to 1.4 doesn't break and things continue to work as expected 

## Actual behavior
Things break

## Steps to reproduce
Attempt to update a SpringBoot app which is using 1.3.2 to 1.4

## Full log output
```
Error loading class .handler.StreamLambdaHandler: org/springframework/boot/context/embedded/EmbeddedServletContainer: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/EmbeddedServletContainer
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.initialize(SpringBootLambdaContainerHandler.java:156)
at com.amazonaws.serverless.proxy.InitializationWrapper.start(InitializationWrapper.java:23)
at com.amazonaws.serverless.proxy.spring.SpringBootProxyHandlerBuilder.buildAndInitialize(SpringBootProxyHandlerBuilder.java:60)
at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.getAwsProxyHandler(SpringBootLambdaContainerHandler.java:80)
at yikes.io.service.handler.StreamLambdaHandler.<clinit>(StreamLambdaHandler.java:21)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.EmbeddedServletContainer
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by peavers** [comment]
Ah nice, I must have missed that in the readme! 

Cheers dude 👍

**Comment by vavadiyahiren** [comment]
Hey i am still getting the same error while uploading to amazon lamda any clue ?

My pom looks like below

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.5.RELEASE</version>
		<relativePath /> 
	</parent>
	<groupId>com.demo.springboot</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>

		
		<dependency>
			<groupId>com.amazonaws.serverless</groupId>
			<artifactId>aws-serverless-java-container-spring</artifactId>
			<version>1.4</version>
		</dependency>

		
		<dependency>
			<groupId>com.amazonaws.serverless</groupId>
			<artifactId>aws-serverless-java-container-springboot2</artifactId>
			<version>1.4</version>
		</dependency>

		
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20190722</version>
		</dependency>


		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<profiles>

		<profile>
			<id>boot</id>
			<activation>
				<property>
					<name>boot</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>default</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-shade-plugin</artifactId>
						<version>2.3</version>
						<configuration>
							<createDependencyReducedPom>false</createDependencyReducedPom>
						</configuration>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>shade</goal>
								</goals>
								<configuration>
									<artifactSet>
										<excludes>
											<exclude>org.apache.tomcat.embed:*</exclude>
										</excludes>
									</artifactSet>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
`

Error on cloud watch looks like below

`Error loading class com.demo.springboot.demo.LambdaHandler: org/springframework/boot/context/embedded/EmbeddedServletContainer: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/EmbeddedServletContainer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.initialize(SpringBootLambdaContainerHandler.java:156)
	at com.amazonaws.serverless.proxy.InitializationWrapper.start(InitializationWrapper.java:23)
	at com.amazonaws.serverless.proxy.spring.SpringBootProxyHandlerBuilder.buildAndInitialize(SpringBootProxyHandlerBuilder.java:60)
	at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.getAwsProxyHandler(SpringBootLambdaContainerHandler.java:80)
	at com.demo.springboot.demo.LambdaHandler.<clinit>(LambdaHandler.java:20)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.EmbeddedServletContainer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more`

**Comment by DBMizrahi** [comment]
Hi @vavadiyahiren,
I think aws-serverless-java-container-spring dependency is redundant. Remove it and redeploy the project. That works for me.

**Comment by vavadiyahiren** [comment]
If i remove that dependency i am getting error like 

`com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
`

**Comment by pjastrzabek** [comment]
I have the same issue. Spring boot 2.1.x / 2.2.x with lib 1.4.0 does not work, 1.3.2 is ok

java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/EmbeddedServletContainer

**Comment by sapessi** [comment]
To confirm, are you using the new `aws-serverless-java-container-springboot2` package? In the latest release we moved support for SpringBoot 2 into a separate module.

**Comment by vavadiyahiren** [comment]
> I have the same issue. Spring boot 2.1.x / 2.2.x with lib 1.4.0 does not work, 1.3.2 is ok
> 
> java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/EmbeddedServletContainer

I got it resolved it was not a problem of any dependency it was a simple configuration mismatch from amazon api gateway.

Please check that and test it independent with removing the API gateway and check the problem still persists but I am sure this has nothing related to the maven dependency either you can go with spring boot 2 or aws-serverless-java-container.

**Comment by ankit-mishra** [comment]
@vavadiyahiren We are also facing same issue testing without API Gateway. Can you please help.

**Comment by sapessi** [comment]
You should also update to version 1.5 of the framework - we released it yesterday :tada: and fixes a few bugs with WebFlux support in Spring Boot 2
