### ISSUE TITLE
Support for @Valid for bean/request body validation in when deployed as a lambda function in AWS

### ISSUE THREAD

**Issue by securethings-amar** [awslabs/aws-serverless-java-container#306]
* Framework version: com.amazonaws.serverless : aws-serverless-java-container-spring : 1.1
* Implementations: Spring Boot

## Scenario
When application deployed as a lambda function and accessed using API Gateway, @Valid does not trigger and does NOT validate request body as per validation tags used like @NotNull, @NotEmpty etc...

## Expected behavior
When deployed as a lambda function; must validate request body came through API Gateway and MethodArgumentInvalidException must be mapped in @ControllerAdvise class to through 400 http status code

## Following is my code:
```java
public class StreamLambdaHandler implements RequestStreamHandler {

	public static final SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
	
	private static Logger log = LoggerFactory.getLogger(StreamLambdaHandler.class);

	static {
		try {
			handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(Application.class);
			handler.onStartup(c -> {
			    FilterRegistration.Dynamic registration = c.addFilter("SimpleCORSFilter", SimpleCORSFilter.class);
			    // update the registration to map to a path
			    registration.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST), true, "/*");
			    // servlet name mappings are disabled and will throw an exception
			});
		} catch (ContainerInitializationException e) {
			// if we fail here. We re-throw the exception to force another cold start
			String errMsg = "Could not initialize Spring Boot application";
			log.error(errMsg);
			throw new RuntimeException("Could not initialize Spring Boot application", e);
		}
	}

	@Override
	public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context) throws IOException {
		AwsProxyRequest request = LambdaContainerHandler.getObjectMapper().readValue(inputStream,
				AwsProxyRequest.class);
		AwsProxyResponse resp = handler.proxy(request, context);
		
		LambdaContainerHandler.getObjectMapper().writeValue(outputStream, resp);
		outputStream.close();
	}
	
	public static void main(String[] args) throws Exception {
		String initialString = "{ \"body\": \"{ \\\"oemId\\\": \\\"123\\\" }\",   \"resource\": \"/{proxy+}\", \"path\": \"/devicespecs\", \"httpMethod\": \"POST\", \"headers\": { \"Content-Type\": \"application/json\", \"Accept\": \"application/json,text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\"},   \"requestContext\": { \"identity\": { \"sourceIp\": \"127.0.0.1\" },   \"authorizer\": { \"payload\": \"{\\\"email\\\":\\\"securethings-amar@gmail.com\\\",\\\"tenant\\\":\\\"OEM22\\\"}\", \"principalId\": \"0f49f816-6aa1-4f6e-9700-f9a25d59ad06\" } } }";
		
		InputStream inputStream = new ByteArrayInputStream(initialString.getBytes());
		OutputStream outputStream = new ByteArrayOutputStream();

		StreamLambdaHandler obj = new StreamLambdaHandler();
		obj.handleRequest(inputStream, outputStream, null);
	}
}
```
=====================

```java
@SpringBootApplication
@EnableWebMvc
@ComponentScan(basePackages = "ai.securethings.serverless")
public class Application extends SpringBootServletInitializer {

    // silence console logging
    @Value("${logging.level.root:OFF}")
    String message = "";

    /*
     * Create required HandlerMapping, to avoid several default HandlerMapping instances being created
     */
    @Bean
    public HandlerMapping handlerMapping() {
        return new RequestMappingHandlerMapping();
    }

    /*
     * Create required HandlerAdapter, to avoid several default HandlerAdapter instances being created
     */
    @Bean
    public HandlerAdapter handlerAdapter() {
        return new RequestMappingHandlerAdapter();
    }

    /*
     * optimization - avoids creating default exception resolvers; not required as the serverless container handles
     * all exceptions
     *
     * By default, an ExceptionHandlerExceptionResolver is created which creates many dependent object, including
     * an expensive ObjectMapper instance.
     */
    /*@Bean
    public HandlerExceptionResolver handlerExceptionResolver() {
        return new HandlerExceptionResolver() {

            @Override
            public ModelAndView resolveException(HttpServletRequest request, HttpServletResponse response, Object handler, Exception ex) {
                return null;
            }
        };
    }*/

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}

```

**Comment by securethings-amar** [comment]
Following is my controller class:
```java
@RestController
@RequestMapping("/devicespecs")
public class DeviceSpecificationController {

	@Autowired
	DeviceSpecificationService deviceSpecService;
	
	@PostMapping
	public ResponseEntity<Void> saveDeviceSpecs(@Valid @RequestBody DeviceSpecification deviceSpecs) {

```

**Comment by securethings-amar** [comment]
When I run my application as a spring boot (web application), it validates request body as per validation annotations used.

Kindly provide me code example of configuration I should use to kick in @Valid annotation even when lambda function gets executed.

**Comment by securethings-amar** [comment]
#16 I did refer this but seems like this is only for unit testing.
How to kick in validation then?

**Comment by securethings-amar** [comment]
Following is my pom.xml:

```xml
<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-indexer</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.amazonaws.serverless</groupId>
			<artifactId>aws-serverless-java-container-spring</artifactId>
			<version>1.1</version>
		</dependency>
		
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>${mysql-connector-java.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${commons-io.version}</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>${json-simple.version}</version>
		</dependency>
	</dependencies>
```

**Comment by sapessi** [comment]
@securethings-amar do you see the same behavior with the latest version of the library (`1.4`)?

The library should not change Spring's behavior, all we do is transform the proxy request object into an `HttpServletRequest` and pass it to Spring's `DispatcherServlet`.

**Comment by securethings-amar** [comment]
> 
> 
> @securethings-amar do you see the same behavior with the latest version of the library (`1.4`)?
> 
> The library should not change Spring's behavior, all we do is transform the proxy request object into an `HttpServletRequest` and pass it to Spring's `DispatcherServlet`.

Is there any breaking changes in v1.4?

Does rest of code pasted in issue work as it is with v1.4?

**Comment by securethings-amar** [comment]
This is my complete pom.xml:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.2.RELEASE</version>
	</parent>

	<groupId>ai.securethings.serverless</groupId>
	<artifactId>serverless-backend-api</artifactId>
	<version>0.0.1</version>
	<name>SecureThings Serverless Backend REST APIs</name>
	<description>Lambda function exposed backend REST apis</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<commons-io.version>2.5</commons-io.version>
		<mysql-connector-java.version>8.0.13</mysql-connector-java.version>
		<json-simple.version>1.1.1</json-simple.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-indexer</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.amazonaws.serverless</groupId>
			<artifactId>aws-serverless-java-container-spring</artifactId>
			<version>1.4</version>
		</dependency>
		
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>${mysql-connector-java.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${commons-io.version}</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>${json-simple.version}</version>
		</dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<configuration>
					<createDependencyReducedPom>false</createDependencyReducedPom>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<artifactSet>
								<excludes>
									<exclude>org.apache.tomcat.embed:*</exclude>
								</excludes>
							</artifactSet>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

After changing version to v1.4, I am getting following error in after lambda execution

```
START RequestId: 7f7a4d37-8784-41aa-b9af-c5bd5f3802ef Version: $LATEST
Error loading class ai.securethings.serverless.handler.StreamLambdaHandler: org/springframework/boot/context/embedded/EmbeddedServletContainer: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/EmbeddedServletContainer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.initialize(SpringBootLambdaContainerHandler.java:156)
	at com.amazonaws.serverless.proxy.InitializationWrapper.start(InitializationWrapper.java:23)
	at com.amazonaws.serverless.proxy.spring.SpringBootProxyHandlerBuilder.buildAndInitialize(SpringBootProxyHandlerBuilder.java:60)
	at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.getAwsProxyHandler(SpringBootLambdaContainerHandler.java:80)
	at ai.securethings.serverless.handler.StreamLambdaHandler.<clinit>(StreamLambdaHandler.java:35)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.EmbeddedServletContainer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

END RequestId: 7f7a4d37-8784-41aa-b9af-c5bd5f3802ef
REPORT RequestId: 7f7a4d37-8784-41aa-b9af-c5bd5f3802ef	Duration: 37.72 ms	Billed Duration: 100 ms	Memory Size: 512 MB	Max Memory Used: 97 MB	Init Duration: 800.01 ms	
Error loading class ai.securethings.serverless.handler.StreamLambdaHandler: org/springframework/boot/context/embedded/EmbeddedServletContainer
java.lang.NoClassDefFoundError

**Comment by securethings-amar** [comment]
@sapessi appreciate if you provide guidance on given full details now.

**Comment by sapessi** [comment]
In version 1.4 SpringBoot 2 support was moved to a [separate package](https://mvnrepository.com/artifact/com.amazonaws.serverless/aws-serverless-java-container-springboot2/1.4). If using 1.4 doesn't fix the issue, I'll dive deeper on this tomorrow to try and replicate the problem.

**Comment by securethings-amar** [comment]
@sapessi : I made required changes in my pom.xml to work with v1.4 but still no luck.
Lambda function does not trigger @Valid validations at all.

Following is my latest pom.xml:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.1.RELEASE</version>
	</parent>

	<groupId>ai.securethings.serverless</groupId>
	<artifactId>serverless-backend-api</artifactId>
	<version>0.0.1</version>
	<name>SecureThings Serverless Backend REST APIs</name>
	<description>Lambda function exposed backend REST apis</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<commons-io.version>2.5</commons-io.version>
		<mysql-connector-java.version>8.0.13</mysql-connector-java.version>
		<json-simple.version>1.1.1</json-simple.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-indexer</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.amazonaws.serverless</groupId>
			<artifactId>aws-serverless-java-container-springboot2</artifactId>
			<version>1.4</version>
		</dependency>
		
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>${mysql-connector-java.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${commons-io.version}</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>${json-simple.version}</version>
		</dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<configuration>
					<createDependencyReducedPom>false</createDependencyReducedPom>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<artifactSet>
								<excludes>
									<exclude>org.apache.tomcat.embed:*</exclude>
								</excludes>
							</artifactSet>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

**Comment by securethings-amar** [comment]
@sapessi : Do you have any working code sample for @Valid annotation in controller class with lambda-spring?

**Comment by sapessi** [comment]
I ran a quick test and it looks like SpringBoot is not throwing an exception (or the exception is getting swallowed somewhere). What I see from my side, is that the method is not executed and we get back an empty response object from Spring (status code 0). By default, we set the status code to 200 when it is <= 0. The validation however, is actually running.

Make sure you include the validation starter in your pom:
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId>
</dependency>
```

Simple model class:
```java
@Validated
public class Person {
    @NotNull
    @NotBlank
    private String name;

    @Max(20)
    private int age;
...
}
```

Simple controller method:
```java
@RequestMapping(path="/person", method=RequestMethod.POST)
public String validPerson(@Valid Person p, BindingResult res) {
    if (res == null) {
        System.out.println("Null binding results");
    }
    if (res.hasErrors()) {
        res.getAllErrors().forEach((oe) -> {
           System.out.println(oe.toString());
        });
        return ERROR_MESSAGE;
    }

    return p.getName();
}
```

While the exception is not thrown, the `BindingResult` does contain the expected errors.  I ran a quick google search and it looks like lots of people are struggling with validation in SpringBoot 2.

```
[main] INFO com.amazonaws.serverless.proxy.internal.LambdaContainerHandler - Starting Lambda Container Handler
[background-preinit] INFO org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.17.Final

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.8.RELEASE)

[main] INFO com.intellij.rt.execution.junit.JUnitStarter - Starting JUnitStarter on dca9048bcbac.ant.amazon.com with PID 48200 (started by bulianis in /Users/bulianis/workspace/aws-serverless-java-container/aws-serverless-java-container-springboot2)
[main] INFO com.intellij.rt.execution.junit.JUnitStarter - No active profile set, falling back to default profiles: default
[main] INFO com.intellij.rt.execution.junit.JUnitStarter - Started JUnitStarter in 3.575 seconds (JVM running for 5.295)

Field error in object 'person' on field 'name': rejected value [null]; codes [NotBlank.person.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [person.name,name]; arguments []; default message [name]]; default message [must not be blank]
Field error in object 'person' on field 'name': rejected value [null]; codes [NotNull.person.name,NotNull.name,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [person.name,name]; arguments []; default message [name]]; default message [must not be null]
[main] INFO com.amazonaws.serverless.proxy.internal.LambdaContainerHandler - 127.0.0.1 - [29/11/2019:17:20:50-0800] "POST /person HTTP/1.1" 200 6 "-" "-" combined

```

**Comment by securethings-amar** [comment]
@sapessi : Thanks for details dude!
Any plan to fix it in upcoming version of library? Feel free to tag this issue.

**Comment by sapessi** [comment]
I'm not sure there's anything I can do in this library. The issue seems to be with SpringBoot 2. I'll do some more digging next week.

**Comment by dotekien** [comment]
I am also having the issue which the validation during binding params in REST api method is muted.

**Comment by dotekien** [comment]
@sapessi if I remove aws-serverless-java-container out of the pom file, the validation works as expected. I am still unable to figure out why :(

**Comment by sapessi** [comment]
Thanks for the feedback @dotekien. It's very weird since all the library doesn't do anything special to start Spring Boot, it just [acts as an embedded container](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-springboot2/src/main/java/com/amazonaws/serverless/proxy/spring/embedded/ServerlessReactiveServletEmbeddedServerFactory.java#L32). I will keep digging but I'm having little luck so far. Any logs or code samples that you can share would help with the investigation.

**Comment by sapessi** [comment]
Hey @dotekien, I finally have a fix for this. About to push it to the `v1.5` branch. It will go out with release 1.5 soon.

**Comment by sharipsg** [comment]
@sapessi I get this issue even in `com.amazonaws.serverless:aws-serverless-java-container-spring:1.5`

@Valid @RequestBody is not throwing error in lambda 

I can get the error in local
![image](https://user-images.githubusercontent.com/14263620/79203164-3fc02400-7e58-11ea-8bc6-8c6ce675795a.png)

**Comment by sapessi** [comment]
Hi @sharipsg - we have [a unit test](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-springboot2/src/test/java/com/amazonaws/serverless/proxy/spring/ServletAppTest.java#L52-L78) that passes on the `@Valid` annotations. Any chance you can share you code (or some code) to help us replicate?

**Comment by sharipsg** [comment]
I still couldn't make it work. Is there any possibility to check this over a screen sharing session?

**Comment by vikiuvb** [comment]
@sapessi The issue still exists in the SprintBoot2 lambda container. I'm using aws-serverless-java-container-springboot2 (v1.5.2), and the validation is not working for Lambda deployments.

**Comment by nguyenquangtrung** [comment]
I finally have a fix for this.
I add 2 library to pom.xml.It run ok
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.el</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>javax.el</groupId>
            <artifactId>javax.el-api</artifactId>
            <version>3.0.0</version>
        </dependency>

**Comment by nguyenquangtrung** [comment]
![pom](https://user-images.githubusercontent.com/18268781/173481897-8cb0e53d-94c4-4010-818b-3b93bca9e5d8.png)
my pom.xml
